name: "CI"
on:
  push:
    branches: "*"
  pull_request:
env:
  cache-version: 1

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.0

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3.3.2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        run: |
          npm run build

      - name: "Check non-empty output"
        run: |
          [ -s dist/appsscript.json ] && [ -s dist/backend.gs ] && [ -s dist/index.html ]

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.0

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3.3.2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Lint"
        run: |
          npm run lint

  backend-test:
    name: "Backend test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.0

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3.3.2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Run tests"
        run: |
          npm run test:backend

      - name: "Upload coverage results"
        uses: codecov/codecov-action@v3.1.4
        with:
          flags: backend

  frontend-test:
    name: "Frontend test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.0

      - name: "Cache NPM dependencies"
        uses: actions/cache@v3.3.2
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          echo "version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')"
          echo "version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" >> $GITHUB_OUTPUT

      - name: Cache playwright binaries
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/ms-playwright"
          key: playwright-binaries-${{ runner.os }}-${{ env.cache-version }}-${{ steps.playwright-version.outputs.version }}

      - name: "Install playwright binaries"
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          npx playwright install --with-deps

      - name: "Install playwright binaries"
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: |
          npx playwright install-deps

      - name: "Run tests"
        run: |
          npm run test:frontend

      - name: "Upload coverage results"
        uses: codecov/codecov-action@v3.1.4
        with:
          flags: frontend

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
